/* =========================================
   GREEN CITY — CITY BUILDER GAME LOGIC
   ========================================= */
(() => {
  'use strict';

  const STORAGE = 'classkru-green-city-v1';
  const $ = (id) => document.getElementById(id);
  const QUESTIONS = [
    { topic: 'การแยกขยะ', q: 'ขวดพลาสติกที่ล้างสะอาดแล้วควรทิ้งลงถังสีใด?', a: 1, options: ['ถังสีเขียว', 'ถังสีน้ำเงิน', 'ถังสีแดง', 'ถังสีเทา'], note: 'ถังสีน้ำเงินรับขยะรีไซเคิล เช่น ขวดพลาสติก กระดาษ และโลหะ' },
    { topic: 'พลังงานสะอาด', q: 'พลังงานชนิดใดหมุนเวียนและไม่ปล่อยควันขณะผลิตไฟฟ้า?', a: 2, options: ['ถ่านหิน', 'น้ำมันดีเซล', 'พลังงานแสงอาทิตย์', 'ก๊าซธรรมชาติ'], note: 'แผงโซลาร์เปลี่ยนแสงอาทิตย์เป็นไฟฟ้าโดยไม่เผาเชื้อเพลิง' },
    { topic: 'การใช้น้ำ', q: 'วิธีใดช่วยประหยัดน้ำในชีวิตประจำวันได้ดีที่สุด?', a: 0, options: ['ปิดก๊อกระหว่างแปรงฟัน', 'เปิดน้ำทิ้งขณะล้างจาน', 'อาบน้ำนานขึ้น', 'ล้างรถทุกวัน'], note: 'การปิดก๊อกในช่วงที่ไม่ใช้น้ำ ลดน้ำสูญเปล่าได้ทันที' },
    { topic: 'ระบบนิเวศ', q: 'พื้นที่สีเขียวในเมืองช่วยเรื่องใดมากที่สุด?', a: 3, options: ['เพิ่มควันพิษ', 'ทำให้น้ำเสีย', 'เพิ่มเสียงรบกวน', 'ลดความร้อนและเป็นที่อยู่อาศัยของสิ่งมีชีวิต'], note: 'ต้นไม้ช่วยให้ร่มเงา ดูดซับคาร์บอน และเพิ่มความหลากหลายทางชีวภาพ' },
    { topic: 'มลพิษอากาศ', q: 'การเดินทางแบบใดช่วยลดการปล่อยคาร์บอนได้?', a: 1, options: ['ขับรถคนเดียวทุกวัน', 'เดิน ปั่นจักรยาน หรือใช้ขนส่งสาธารณะ', 'ติดเครื่องรถขณะจอด', 'ใช้รถระยะใกล้เสมอ'], note: 'การแชร์การเดินทางและใช้พลังงานน้อย ลดมลพิษทางอากาศได้' },
    { topic: 'สิ่งมีชีวิต', q: 'เหตุใดจึงไม่ควรทิ้งขยะลงแม่น้ำ?', a: 2, options: ['น้ำจะไหลเร็วขึ้น', 'ทำให้ฝนตกมากขึ้น', 'ทำร้ายสัตว์น้ำและทำให้น้ำปนเปื้อน', 'ช่วยให้ต้นไม้โต'], note: 'ขยะในแม่น้ำเป็นอันตรายต่อระบบนิเวศและอาจย้อนกลับมาสู่อาหารของเรา' },
    { topic: 'ภาวะโลกร้อน', q: 'ก๊าซชนิดใดเพิ่มขึ้นจากการเผาไหม้เชื้อเพลิงฟอสซิลและเกี่ยวข้องกับโลกร้อน?', a: 0, options: ['คาร์บอนไดออกไซด์', 'ออกซิเจน', 'ไนโตรเจน', 'ไอน้ำจากเมฆ'], note: 'การลดการเผาไหม้ถ่านหินและน้ำมัน ช่วยลดคาร์บอนไดออกไซด์ได้' },
    { topic: 'อาหารอย่างยั่งยืน', q: 'การเลือกอาหารแบบใดช่วยลดขยะบรรจุภัณฑ์?', a: 3, options: ['ซื้อของห่อเล็กหลายชิ้น', 'ใช้ถุงพลาสติกทุกครั้ง', 'ทิ้งอาหารเหลือทันที', 'พกภาชนะและเลือกสินค้าที่บรรจุภัณฑ์น้อย'], note: 'การใช้ซ้ำและลดบรรจุภัณฑ์ ช่วยลดขยะตั้งแต่ต้นทาง' }
  ];
  const BUILDINGS = [
    { id: 'tree', icon: '🌳', name: 'ปลูกต้นไม้', cost: 30, level: 1, label: 'ต้นไม้', effects: { green: 5, air: 2, carbon: 2 }, message: 'ต้นอ่อนเติบโต อากาศของเมืองสดชื่นขึ้น' },
    { id: 'park', icon: '🌲', name: 'สวนสาธารณะ', cost: 80, level: 1, label: 'สวน', effects: { green: 10, happy: 10, air: 3 }, message: 'สวนสาธารณะเปิดแล้ว! ผู้คนมาพักผ่อนอย่างมีความสุข' },
    { id: 'solar', icon: '☀️', name: 'โซลาร์เซลล์', cost: 120, level: 2, label: 'โซลาร์', effects: { energy: 15, carbon: 10, air: 2 }, message: 'แผงโซลาร์ผลิตพลังงานสะอาดให้เมือง' },
    { id: 'recycle', icon: '♻️', name: 'ศูนย์รีไซเคิล', cost: 150, level: 2, label: 'รีไซเคิล', effects: { recycle: 20, air: 4, carbon: 8 }, message: 'ศูนย์รีไซเคิลเริ่มทำงาน ขยะถูกเปลี่ยนเป็นทรัพยากร' },
    { id: 'water', icon: '💧', name: 'บำบัดน้ำ', cost: 180, level: 3, label: 'บำบัดน้ำ', effects: { water: 22, happy: 4 }, message: 'ระบบบำบัดน้ำฟื้นฟูแม่น้ำให้ใสสะอาด' },
    { id: 'bike', icon: '🚲', name: 'ทางจักรยาน', cost: 100, level: 3, label: 'จักรยาน', effects: { happy: 8, carbon: 9, air: 4 }, message: 'ทางจักรยานใหม่ทำให้การเดินทางปลอดมลพิษขึ้น' }
  ];
  const EVENTS = [
    { icon: '🔥', title: 'เตือนภัยไฟป่า', detail: 'ตอบภารกิจนี้ให้ถูกเพื่อช่วยวางแผนฟื้นฟูพื้นที่สีเขียว', bonus: 'green' },
    { icon: '🌧️', title: 'พายุฝนมาเยือน', detail: 'ภารกิจถัดไปจะช่วยให้ชุมชนรับมือกับน้ำได้ดีขึ้น', bonus: 'water' },
    { icon: '🐦', title: 'นกหายากกลับมา', detail: 'รักษาพื้นที่สีเขียวไว้เพื่อให้สัตว์มีบ้านที่ปลอดภัย', bonus: 'happy' },
    { icon: '🦋', title: 'ฤดูผีเสื้อ', detail: 'ธรรมชาติเริ่มฟื้นตัว ตอบถูกเพื่อรับ Eco Point เพิ่ม', bonus: 'green' }
  ];
  const EMPTY_CELLS = 20;
  const ui = {
    grid: $('city-grid'), eco: $('eco-value'), level: $('level-value'), score: $('score-value'), population: $('population-value'), happiness: $('happiness-value'), weather: $('weather'), message: $('city-message'),
    missionNumber: $('mission-number'), progress: $('mission-progress'), event: $('event-banner'), topic: $('question-topic'), question: $('question-text'), answers: $('answer-list'), feedback: $('answer-feedback'), buildings: $('building-list'), selected: $('selected-building'),
    achievements: $('achievement-list'), statsToggle: $('stats-toggle'), statsPanel: $('stats-panel'), start: $('start-overlay'), startButton: $('start-button'), sound: $('sound-button')
  };
  const state = { eco: 0, score: 0, level: 1, population: 120, buildings: [], selected: null, correct: 0, answered: 0, mission: 1, questionIndex: 0, locked: false, event: null, sound: true, metrics: { air: 25, water: 30, green: 12, recycle: 10, energy: 15, happy: 35, carbon: 18 } };
  let audio = null;

  function random(list) { return list[Math.floor(Math.random() * list.length)]; }
  function loadRecord() { try { return { highScore: 0, highEco: 0, trees: 0, built: 0, played: 0, completed: 0, achievements: [], ...JSON.parse(localStorage.getItem(STORAGE) || '{}') }; } catch { return { highScore: 0, highEco: 0, trees: 0, built: 0, played: 0, completed: 0, achievements: [] }; } }
  function saveRecord() { const record = loadRecord(); const treesBuilt = state.buildings.filter((item) => item === 'tree').length; const totalBuilt = state.buildings.filter(Boolean).length; record.highScore = Math.max(record.highScore, state.score); record.highEco = Math.max(record.highEco, state.eco); record.trees = Math.max(record.trees, treesBuilt); record.built = Math.max(record.built, totalBuilt); record.achievements = [...new Set([...record.achievements, ...achievementState().filter((item) => item.unlocked).map((item) => item.id)])]; localStorage.setItem(STORAGE, JSON.stringify(record)); }
  function initAudio() { if (!state.sound || audio) return; const Context = window.AudioContext || window.webkitAudioContext; if (Context) audio = new Context(); }
  function beep(frequency, duration, type = 'sine', volume = .04, rise = 0) { if (!state.sound) return; initAudio(); if (!audio) return; if (audio.state === 'suspended') audio.resume(); const time = audio.currentTime; const osc = audio.createOscillator(); const gain = audio.createGain(); osc.type = type; osc.frequency.setValueAtTime(frequency, time); if (rise) osc.frequency.exponentialRampToValueAtTime(frequency + rise, time + duration); gain.gain.setValueAtTime(.001, time); gain.gain.exponentialRampToValueAtTime(volume, time + .02); gain.gain.exponentialRampToValueAtTime(.001, time + duration); osc.connect(gain).connect(audio.destination); osc.start(time); osc.stop(time + duration + .03); }
  const sound = { click: () => beep(430, .06, 'triangle', .03), right: () => { beep(520, .14, 'sine', .05, 250); setTimeout(() => beep(740, .14, 'sine', .04), 80); }, wrong: () => beep(170, .25, 'sawtooth', .045, -70), build: () => { beep(300, .11, 'triangle', .04, 260); setTimeout(() => beep(580, .17, 'sine', .04), 90); }, level: () => [440, 554, 659, 880].forEach((f, i) => setTimeout(() => beep(f, .15, 'triangle', .055), i * 90)) };

  function levelForEco() { return state.eco >= 600 ? 5 : state.eco >= 400 ? 4 : state.eco >= 230 ? 3 : state.eco >= 100 ? 2 : 1; }
  function cityTitle() { return ['หมู่บ้านเริ่มต้น', 'ชุมชนสีเขียว', 'เมืองสีเขียว', 'Smart Green City', 'Eco Metropolis'][state.level - 1]; }
  function updateHeader() { state.level = levelForEco(); ui.eco.textContent = state.eco; ui.level.textContent = state.level; ui.score.textContent = state.score.toLocaleString('th-TH'); ui.population.textContent = state.population.toLocaleString('th-TH'); ui.happiness.textContent = `${state.metrics.happy}%`; ui.weather.textContent = state.metrics.air >= 65 ? '☀️ อากาศสดใส' : state.metrics.air >= 45 ? '🌤️ อากาศดีขึ้น' : '☁️ เมืองมีหมอกควัน'; }
  function updateMetrics() { document.querySelectorAll('.indicator').forEach((row) => { const key = row.dataset.key; const value = state.metrics[key]; row.querySelector('i').style.width = `${value}%`; row.querySelector('b').textContent = value; }); updateHeader(); }
  function cellIcon(index) { const id = state.buildings[index]; if (id) return BUILDINGS.find((item) => item.id === id); return null; }
  function renderGrid() { ui.grid.innerHTML = ''; for (let index = 0; index < EMPTY_CELLS; index += 1) { const item = cellIcon(index); const cell = document.createElement('button'); cell.type = 'button'; cell.className = `city-cell ${item ? 'is-built' : index < 7 ? 'is-polluted' : 'is-empty'}`; cell.dataset.index = index; cell.disabled = Boolean(item); cell.setAttribute('aria-label', item ? `${item.name} สร้างแล้ว` : `พื้นที่ ${index + 1} สำหรับก่อสร้าง`); cell.innerHTML = item ? `${item.icon}<span class="building-label">${item.label}</span>` : (index < 7 ? '🏭' : '＋'); cell.addEventListener('click', buildAt); ui.grid.append(cell); } }
  function renderBuildings() { ui.buildings.innerHTML = ''; BUILDINGS.forEach((building) => { const button = document.createElement('button'); const locked = state.level < building.level; button.className = `building-button ${state.selected === building.id ? 'selected' : ''}`; button.type = 'button'; button.disabled = locked; button.dataset.building = building.id; button.setAttribute('aria-pressed', String(state.selected === building.id)); button.innerHTML = `<span class="building-icon">${building.icon}</span><b>${building.name}</b><small>${locked ? `ปลดล็อก Level ${building.level}` : effectText(building.effects)}</small><span class="building-cost">${building.cost} Eco</span>`; button.addEventListener('click', () => selectBuilding(building.id)); ui.buildings.append(button); }); }
  function effectText(effects) { return Object.entries(effects).slice(0, 2).map(([key, value]) => `+${value} ${({ air: 'อากาศ', water: 'น้ำ', green: 'พื้นที่เขียว', recycle: 'รีไซเคิล', energy: 'พลังงาน', happy: 'ความสุข', carbon: 'ลดคาร์บอน' })[key]}`).join(' · '); }
  function selectBuilding(id) { state.selected = id; const building = BUILDINGS.find((item) => item.id === id); ui.selected.textContent = `เลือก ${building.name} (${building.cost} Eco) แล้วกดพื้นที่ว่างบนแผนที่`; renderBuildings(); sound.click(); }
  function buildAt(event) { const index = Number(event.currentTarget.dataset.index); const building = BUILDINGS.find((item) => item.id === state.selected); if (!building) { ui.message.textContent = 'เลือกโครงการจากแถบด้านล่างก่อน แล้วจึงเลือกพื้นที่ว่าง'; return; } if (state.eco < building.cost) { ui.message.textContent = `Eco Point ยังไม่พอ ต้องการอีก ${building.cost - state.eco} คะแนน`; sound.wrong(); return; } state.eco -= building.cost; state.population += building.id === 'park' ? 35 : 12; state.buildings[index] = building.id; Object.entries(building.effects).forEach(([key, value]) => { state.metrics[key] = Math.min(100, state.metrics[key] + value); }); state.metrics.happy = Math.min(100, state.metrics.happy + 1); ui.message.textContent = building.message; state.selected = null; renderGrid(); renderBuildings(); updateMetrics(); renderAchievements(); saveRecord(); sound.build(); }
  function currentQuestion() { return QUESTIONS[state.questionIndex % QUESTIONS.length]; }
  function renderQuestion() { const question = currentQuestion(); ui.topic.textContent = question.topic; ui.question.textContent = question.q; ui.answers.innerHTML = ''; ui.feedback.textContent = ''; question.options.forEach((option, index) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'answer-button'; button.innerHTML = `<b>${index + 1}</b><span>${option}</span>`; button.addEventListener('click', () => answer(index)); ui.answers.append(button); }); ui.missionNumber.textContent = state.mission; ui.progress.textContent = `${state.correct % 3} / 3`; }
  function answer(index) { if (state.locked) return; state.locked = true; const question = currentQuestion(); const buttons = [...ui.answers.querySelectorAll('button')]; buttons.forEach((button) => { button.disabled = true; }); state.answered += 1; if (index === question.a) { const eventBonus = state.event ? 25 : 0; const metric = state.event?.bonus; state.eco += 50 + eventBonus; state.score += 100 + eventBonus; state.correct += 1; state.population += 5; if (metric) state.metrics[metric] = Math.min(100, state.metrics[metric] + 8); buttons[index].classList.add('correct'); ui.feedback.textContent = `ยอดเยี่ยม! +${50 + eventBonus} Eco Point · ${question.note}`; ui.message.textContent = state.event ? 'คุณรับมือเหตุการณ์ได้สำเร็จ เมืองแข็งแกร่งขึ้น!' : 'ภารกิจสำเร็จ! นำ Eco Point ไปสร้างโครงการสีเขียวได้เลย'; sound.right(); state.event = null; ui.event.hidden = true; } else { buttons[index].classList.add('wrong'); buttons[question.a].classList.add('correct'); state.metrics.happy = Math.max(0, state.metrics.happy - 2); ui.feedback.textContent = `ยังไม่ถูก ลองจดจำไว้: ${question.note}`; ui.message.textContent = 'เมืองยังต้องการความช่วยเหลือ ตอบภารกิจถัดไปเพื่อฟื้นฟูต่อ'; sound.wrong(); }
    const oldLevel = state.level; updateMetrics(); if (state.level > oldLevel) { ui.message.textContent = `ยินดีด้วย! ปลดล็อก ${cityTitle()} และโครงการใหม่`; sound.level(); } renderBuildings(); renderAchievements(); saveRecord(); setTimeout(nextMission, 1450);
  }
  function nextMission() { state.questionIndex += 1; state.mission += 1; state.locked = false; if (state.mission % 4 === 0) triggerEvent(); renderQuestion(); }
  function triggerEvent() { state.event = random(EVENTS); ui.event.hidden = false; ui.event.textContent = `${state.event.icon} ${state.event.title}: ${state.event.detail} (ตอบถูก +25 Eco Point)`; }
  function achievementState() { return [ { id: 'seed', icon: '🌱', label: 'นักปลูก', unlocked: state.buildings.filter((id) => id === 'tree').length >= 3 }, { id: 'recycle', icon: '♻️', label: 'นักรีไซเคิล', unlocked: state.metrics.recycle >= 50 }, { id: 'clean', icon: '💨', label: 'อากาศดี', unlocked: state.metrics.air >= 60 }, { id: 'city', icon: '🏙️', label: 'เมืองสีเขียว', unlocked: state.level >= 3 } ]; }
  function renderAchievements() { ui.achievements.innerHTML = achievementState().map((item) => `<span class="achievement ${item.unlocked ? 'unlocked' : ''}" title="${item.label}">${item.icon} ${item.label}</span>`).join(''); }
  function renderStats() { const record = loadRecord(); const accuracy = state.answered ? Math.round(state.correct / state.answered * 100) : 0; ui.statsPanel.innerHTML = `<div class="stat"><span>High Score</span><strong>${record.highScore}</strong></div><div class="stat"><span>Eco สูงสุด</span><strong>${record.highEco}</strong></div><div class="stat"><span>ต้นไม้สร้าง</span><strong>${record.trees}</strong></div><div class="stat"><span>อาคารสร้าง</span><strong>${record.built}</strong></div><div class="stat"><span>คำตอบถูก</span><strong>${state.correct}</strong></div><div class="stat"><span>ความแม่นยำ</span><strong>${accuracy}%</strong></div>`; }
  function startGame() { initAudio(); const record = loadRecord(); record.played += 1; localStorage.setItem(STORAGE, JSON.stringify(record)); ui.start.classList.add('hidden'); renderQuestion(); renderGrid(); renderBuildings(); updateMetrics(); renderAchievements(); ui.message.textContent = 'ภารกิจแรกกำลังรอคุณอยู่ ตอบให้ถูกเพื่อรับ Eco Point'; sound.click(); }
  function keyboard(event) { if (event.repeat || !ui.start.classList.contains('hidden')) return; if (/^[1-4]$/.test(event.key)) { const button = ui.answers.querySelectorAll('button')[Number(event.key) - 1]; if (button && !button.disabled) button.click(); } }

  ui.startButton.addEventListener('click', startGame); ui.sound.addEventListener('click', () => { state.sound = !state.sound; ui.sound.textContent = state.sound ? '🔊' : '🔇'; ui.sound.setAttribute('aria-pressed', String(state.sound)); ui.sound.setAttribute('aria-label', state.sound ? 'ปิดเสียง' : 'เปิดเสียง'); if (state.sound) { initAudio(); sound.click(); } }); ui.statsToggle.addEventListener('click', () => { ui.statsPanel.hidden = !ui.statsPanel.hidden; if (!ui.statsPanel.hidden) renderStats(); }); document.addEventListener('keydown', keyboard);
  renderGrid(); renderBuildings(); updateMetrics(); renderAchievements();
})();
