'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
const crypto=require('node:crypto');
const {validateArtifact,hash,render}=require('../api/_lib/media-artifact');
const fixture=require('./media-fixture.cjs');
const service=require('../api/_lib/media-service');
test('artifact policy rejects executable markup, external CSS and forbidden APIs',()=>{
  const artifact=validateArtifact(fixture);assert.equal(hash(artifact).length,64);
  for(const html of ['<script>alert(1)</script>','<img src="https://evil.test">','<svg><foreignObject>bad</foreignObject></svg>','<button onclick="alert(1)">x</button>','<input type="password">'])assert.throws(()=>validateArtifact({...fixture,html}));
  for(const js of ['fetch("/api");','new Function("return 1")();','import("x");','top.location="https://evil.test"','const = 1;'])assert.throws(()=>validateArtifact({...fixture,js}));
  assert.throws(()=>validateArtifact({...fixture,css:'body{background:url(https://evil.test)}'}));
  const output=render(artifact);assert.match(output.csp,/sandbox allow-scripts/);assert.match(output.csp,/connect-src 'none'/);assert.doesNotMatch(output.csp,/allow-same-origin/);
  assert.notEqual(render(artifact).csp,output.csp);
});
test('context strips personal fields and media origin cannot be app origin',()=>{
  assert.deepEqual(Object.keys(service.context({students:['private'],subject:'วิทยาศาสตร์'})),['subject','classroom','goal','duration_minutes']);
  process.env.CLASSKRU_APP_ORIGIN='https://app.example.test';process.env.MEDIA_ORIGIN='https://app.example.test';
  assert.throws(()=>service.mediaOrigin());process.env.MEDIA_ORIGIN='https://media.example.test';assert.equal(service.mediaOrigin(),'https://media.example.test');
});
test('real SQL: owner isolation, idempotent jobs, queue claims, immutable versions, publish and revoke',async()=>{
  const db=new PGlite();
  try{
    await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
      create schema auth; create table auth.users(id uuid primary key); grant usage on schema auth to authenticated;
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
      create table storage.objects(id text,bucket_id text); alter table storage.objects enable row level security;
      grant usage on schema storage to authenticated; grant select,insert on storage.objects to authenticated;
      create policy legacy_broad_policy on storage.objects for all to authenticated using (true) with check (true);
      insert into storage.objects values ('private-source','media-bundles'),('other-file','other-bucket');`);
    await db.exec(fs.readFileSync(require.resolve('../supabase/migrations/202609190001_media_studio.sql'),'utf8'));
    const a=crypto.randomUUID(),b=crypto.randomUUID();
    await db.query('insert into auth.users values ($1),($2)',[a,b]);
    const create=await db.query('select * from media_create_project($1,$2,$3)',[a,'ครู A','{}']);const project=create.rows[0].id;
    const projectB=(await db.query('select * from media_create_project($1,$2,$3)',[b,'ครู B','{}'])).rows[0].id;
    await assert.rejects(db.query('select * from media_enqueue($1,$2,$3,$4,$5)',[b,project,'build','สร้างเกม',crypto.randomUUID()]),/not_found/);
    const key=crypto.randomUUID();
    const enqueue=()=>db.query('select * from media_enqueue($1,$2,$3,$4,$5)',[a,project,'build','สร้างเกม',key]);
    const job=(await enqueue()).rows[0];assert.equal((await enqueue()).rows[0].id,job.id);
    assert.equal((await db.query('select count(*)::int as n from media_turns')).rows[0].n,1);
    await assert.rejects(db.query('select * from media_enqueue($1,$2,$3,$4,$5)',[a,project,'build','สร้างอีก',crypto.randomUUID()]),/project_busy/);
    const claim=crypto.randomUUID();
    assert.equal((await db.query('select * from media_claim($1,$2,$3)',[b,job.id,claim])).rows.length,0);
    assert.equal((await db.query('select * from media_claim($1,$2,$3)',[a,job.id,claim])).rows.length,1);
    assert.equal((await db.query('select * from media_claim($1,$2,$3)',[a,job.id,crypto.randomUUID()])).rows.length,0);
    const version={id:crypto.randomUUID(),title:'สื่อ',summary:'ทดสอบ',storage_path:`${a}/${project}/v.json`,sha256:'a'.repeat(64),review:{browser_check:'passed',policy_version:1}};
    const finish=await db.query('select media_finish($1,$2,$3,$4,$5,$6) as ok',[a,job.id,claim,'สร้างแล้ว',null,JSON.stringify(version)]);assert.equal(finish.rows[0].ok,true);
    assert.equal((await db.query('select media_finish($1,$2,$3,$4,$5,$6) as ok',[a,job.id,claim,'ซ้ำ',null,JSON.stringify(version)])).rows[0].ok,false);
    await db.exec(`set role authenticated; set request.jwt.claim.sub='${b}';`);
    assert.equal((await db.query('select * from media_projects')).rows.length,1);
    assert.equal((await db.query('select * from media_versions')).rows.length,0);
    assert.deepEqual((await db.query('select id from storage.objects')).rows.map(r=>r.id),['other-file']);
    await assert.rejects(db.query("insert into storage.objects values ('forged','media-bundles')"),/row-level security/);
    await assert.rejects(db.query("update media_projects set title='hacked' where id=$1",[project]),/permission denied/);
    await assert.rejects(db.query('select * from media_create_project($1,$2,$3)',[a,'forged','{}']),/permission denied/);
    await db.exec('reset role');
    await assert.rejects(db.query('select * from media_publish($1,$2,$3)',[b,version.id,'b'.repeat(64)]),/not_found/);
    const published=(await db.query('select * from media_publish($1,$2,$3)',[a,version.id,'b'.repeat(64)])).rows[0];
    assert.equal((await db.query('select * from media_publish($1,$2,$3)',[a,version.id,'c'.repeat(64)])).rows[0].id,published.id);
    const c=crypto.randomUUID();await db.query('insert into auth.users values ($1)',[c]);
    const projectC=(await db.query('select * from media_create_project($1,$2,$3)',[c,'ครู C','{}'])).rows[0].id;
    const projectA2=(await db.query('select * from media_create_project($1,$2,$3)',[a,'งาน A2','{}'])).rows[0].id;
    const queue=async(owner,p)=>(await db.query('select * from media_enqueue($1,$2,$3,$4,$5)',[owner,p,'plan','วางแผน',crypto.randomUUID()])).rows[0];
    const ja=await queue(a,project),ja2=await queue(a,projectA2),jb=await queue(b,projectB),jc=await queue(c,projectC);
    const claimJob=(owner,j)=>db.query('select * from media_claim($1,$2,$3)',[owner,j.id,crypto.randomUUID()]);
    assert.equal((await claimJob(a,ja)).rows.length,1);
    assert.equal((await claimJob(a,ja2)).rows.length,0,'one running job per teacher');
    assert.equal((await claimJob(b,jb)).rows.length,1);
    assert.equal((await claimJob(c,jc)).rows.length,0,'at most two running globally');
    await db.query("update media_jobs set started_at=now()-interval '6 minutes' where id=$1",[ja.id]);
    assert.equal((await claimJob(c,jc)).rows.length,1,'expired claim releases capacity');
    assert.equal((await db.query('select error_code from media_jobs where id=$1',[ja.id])).rows[0].error_code,'job_expired');
    await db.query('select media_archive($1,$2,true)',[a,project]);
    assert.ok((await db.query('select revoked_at from media_links')).rows[0].revoked_at);
    assert.equal((await db.query('select count(*)::int as n from media_versions')).rows[0].n,1);
    // Student sessions cannot enumerate metadata or bundles.
    await db.exec('set role anon');await assert.rejects(db.query('select * from media_links'),/permission denied/);await db.exec('reset role');
    assert.ok(projectB);
  } finally{await db.close();}
});
test('AI adapter reuses OpenRouter, keeps keys server-side and fails closed on incomplete output',async t=>{
  const ai=require('../api/_lib/media-ai');
  const names=['OPENROUTER_API_KEY','OPENAI_API_KEY','OPENROUTER_MEDIA_MODEL'];
  const old=Object.fromEntries(names.map(key=>[key,process.env[key]]));
  t.after(()=>{for(const key of names){if(old[key]===undefined)delete process.env[key];else process.env[key]=old[key];}});
  process.env.OPENROUTER_API_KEY='test-router-key';process.env.OPENAI_API_KEY='test-openai-key';process.env.OPENROUTER_MEDIA_MODEL='test-model';
  let endpoint,request;
  const fetchMock=t.mock.method(globalThis,'fetch',async(url,options)=>{endpoint=url;request=JSON.parse(options.body);return {ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify(fixture)}}]})};});
  assert.deepEqual(await ai.ask('build',{message:'สร้างเกม'}),fixture);
  assert.equal(endpoint,'https://openrouter.ai/api/v1/chat/completions');assert.equal(request.model,'test-model');
  assert.deepEqual(request.provider,{data_collection:'deny'});assert.ok(!JSON.stringify(request).includes('test-router-key'));
  fetchMock.mock.mockImplementation(async()=>({ok:true,json:async()=>({choices:[{finish_reason:'length',message:{content:'{}'}}]})}));
  await assert.rejects(ai.ask('build',{}),{code:'ai_incomplete'});
  delete process.env.OPENROUTER_API_KEY;
  fetchMock.mock.mockImplementation(async(url,options)=>{endpoint=url;request=JSON.parse(options.body);return {ok:true,json:async()=>({status:'completed',output_text:JSON.stringify(fixture)})};});
  await ai.ask('build',{});assert.equal(endpoint,'https://api.openai.com/v1/responses');assert.equal(request.store,false);assert.equal(request.text.format.strict,true);
  delete process.env.OPENAI_API_KEY;await assert.rejects(ai.ask('plan',{}),{code:'ai_not_configured'});
});
test('public delivery validates capability, expiry, owner, artifact hash and review without leaking metadata',async t=>{
  const db=require('../api/_lib/media-db'),handler=require('../api/media-studio/public');
  const token='d'.repeat(64),artifact=validateArtifact(fixture);
  let link={project_id:'project',version_id:'version',teacher_id:'private-owner'},version={project_id:'project',storage_path:'private-path',sha256:hash(artifact),review:{browser_check:'passed',policy_version:1}};
  t.mock.method(db,'rows',async(table,filter)=>{assert.equal(filter.revoked_at,'is.null');return link?[link]:[];});
  t.mock.method(db,'owned',async(table,id,owner)=>{assert.equal(owner,'private-owner');return table==='media_projects'?{id:'project',archived:false}:version;});
  t.mock.method(db,'bundle',async()=>artifact);
  const call=async()=>{const res={setHeader(){},status(n){this.statusCode=n;return this;},json(body){this.body=body;}};await handler({method:'GET',query:{token}},res);return res;};
  let res=await call();assert.equal(res.statusCode,200);assert.doesNotMatch(JSON.stringify(res.body),/private-owner|private-path/);
  version.sha256='0'.repeat(64);assert.equal((await call()).statusCode,503);version.sha256=hash(artifact);
  link.expires_at=new Date(Date.now()-1000).toISOString();assert.equal((await call()).statusCode,404);
  link=null;assert.equal((await call()).statusCode,404,'revoked or unknown capability');
});
test('HTTP rejects unauthenticated requests and cross-origin writes',async()=>{
  const handler=require('../api/media-studio');
  const recorder=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(body){this.body=body;}});
  let res=recorder();await handler({method:'POST',headers:{host:'app.test',origin:'https://evil.test'},body:{}},res);assert.equal(res.statusCode,403);
  res=recorder();await handler({method:'POST',headers:{host:'app.test'},body:{}},res);assert.equal(res.statusCode,401);
});
test('PostgREST composite RPC responses normalize singleton arrays without changing claim/boolean results',async t=>{
  const db=require('../api/_lib/media-db'),old=process.env.SUPABASE_SECRET_KEY;
  process.env.SUPABASE_SECRET_KEY='sb_secret_test_only';
  t.after(()=>{if(old===undefined)delete process.env.SUPABASE_SECRET_KEY;else process.env.SUPABASE_SECRET_KEY=old;});
  let response=[{id:'one'}];
  t.mock.method(globalThis,'fetch',async()=>({ok:true,status:200,json:async()=>response}));
  for(const name of ['media_create_project','media_enqueue','media_publish'])assert.deepEqual(await db.rpc(name,{}),{id:'one'});
  assert.deepEqual(await db.rpc('media_claim',{}),[{id:'one'}]);
  response=true;assert.equal(await db.rpc('media_finish',{}),true);
  response=[];await assert.rejects(db.rpc('media_enqueue',{}),{code:'database_unavailable'});
});
