'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const db=require('../api/_lib/media-db');
const leases=require('../api/_lib/media-lease');
const service=require('../api/_lib/media-service');
const ai=require('../api/_lib/media-ai');
const plannerAi=require('../api/_lib/media-planner-ai');
const browser=require('../api/_lib/media-check');
const artifact=require('../api/_lib/media-artifact');
const sample=require('./media-fixture.cjs');
const fixture=require('./media-storage-fixture.cjs');
const uuid=()=>crypto.randomUUID();
const plan={assistant_message:'ลองปรับความสูงแล้วสังเกตความเร็วดีไหม',title:'รถไฟพลังงาน',objective:'พลังงานเปลี่ยนรูป',observation:'ความสูงลด ความเร็วเพิ่ม',variables:['ความสูง','มวล'],mission:'ถึงสถานี',next_questions:['จะให้เด็กปรับแรงเสียดทานไหม']};
function providers(t) {
  let calls=0;
  t.mock.method(ai,'ask',async kind=>{calls++;return kind==='plan'?plan:sample;});
  t.mock.method(plannerAi,'ask',async()=>{calls++;return {assistant_message:plan.assistant_message,media_brief:{topic:plan.title,audience:'',learning_message:plan.objective,media_type:'',concept:plan.mission,content_structure:plan.observation,visual_direction:'',interaction_direction:'',tone:'',constraints:plan.variables},suggested_directions:[],open_questions:plan.next_questions,ready_to_build:false};});
  t.mock.method(browser,'checkInBrowser',async()=>({browser_check:'passed',policy_version:artifact.POLICY_VERSION}));
  return ()=>calls;
}
test('private bucket auto-creation, authenticated encryption, no plaintext or overwrite, fail closed on public bucket',async t=>{
  const f=fixture(t);await db.ensureBucket();assert.equal(f.bucket.public,false);
  assert.equal(await db.put('test/one.json',{private:'teacher conversation'}),true);
  assert.equal(await db.put('test/one.json',{private:'overwrite'}),false);
  assert.deepEqual(await db.get('test/one.json'),{private:'teacher conversation'});
  assert.ok(!JSON.stringify([...f.objects.values()]).includes('teacher conversation'));
  f.objects.set('test/two.json',structuredClone(f.objects.get('test/one.json')));
  await assert.rejects(db.get('test/two.json'),{code:'storage_integrity_failed'},'envelope cannot be moved to forge another record');
  const sealed=f.objects.get('test/one.json');sealed.data='broken';
  await assert.rejects(db.get('test/one.json'),{code:'storage_integrity_failed'});
  await assert.rejects(db.get('../secret'),{code:'invalid_storage_path'});
  f.bucket.public=true;await assert.rejects(db.ensureBucket(),{code:'storage_bucket_unsafe'});
});
test('append-only lease elects one concurrent owner; stale release cannot unlock successor',async t=>{
  fixture(t);await db.ensureBucket();
  const attempts=await Promise.all(Array.from({length:8},()=>leases.acquire('test/race')));
  assert.equal(attempts.filter(Boolean).length,1);
  const first=attempts.find(Boolean);await leases.release(first);
  const second=await leases.acquire('test/race');assert.ok(second);assert.notEqual(first.seq,second.seq);
  await leases.release(first);assert.equal(await leases.acquire('test/race'),null);
  const actual=Date.now();t.mock.method(Date,'now',()=>actual+leases.TTL+1000);
  const third=await leases.acquire('test/race');assert.ok(third);
  await leases.release(second);assert.equal(await leases.acquire('test/race'),null);
});
test('Storage-only chat/build/reopen/version/share/revoke/archive flow keeps tenants isolated',async t=>{
  const f=fixture(t),calls=providers(t),a=uuid(),b=uuid();
  const p=await service.create(a,'พลังงาน',{subject:'วิทยาศาสตร์',students:['never store']});
  await service.create(b,'ครู B',{});
  assert.equal((await service.list(a)).length,1);
  await assert.rejects(service.state(b,p.id),{code:'not_found'});
  await assert.rejects(service.enqueue(b,p.id,'plan','แอบเขียน',uuid()),{code:'not_found'});
  const request=uuid(),j=await service.enqueue(a,p.id,'plan','คิดเกมให้หน่อย',request);
  assert.equal((await service.enqueue(a,p.id,'plan','คิดเกมให้หน่อย',request)).id,j.id);
  await assert.rejects(service.enqueue(a,p.id,'plan','ข้อความเปลี่ยน',request),{code:'request_conflict'});
  await assert.rejects(service.enqueue(a,p.id,'plan','อีกคำขอ',uuid()),{code:'project_busy'});
  await service.run(a,p.id,j.id);await service.run(a,p.id,j.id);assert.equal(calls(),1);
  const s=await service.state(a,p.id);assert.equal(s.turns.length,2);assert.equal(s.project.plan.title,plan.title);assert.equal(s.project.context.students,undefined);
  const build=await service.enqueue(a,p.id,'build','สร้างเกม',uuid());await service.run(a,p.id,build.id);
  const generated=await service.state(a,p.id);assert.equal(generated.versions.length,1);assert.equal(generated.turns.length,4);
  const link=await service.issueLink(a,p.id,build.id,'published'),token=new URL(link.url).searchParams.get('token');
  assert.equal((await service.issueLink(a,p.id,build.id,'published')).id,link.id);
  await assert.rejects(service.issueLink(b,p.id,build.id,'published'),{code:'not_found'});
  await assert.rejects(service.revoke(b,p.id,link.id),{code:'not_found'});
  assert.equal((await service.publicArtifact(token)).title,sample.title);
  const res={setHeader(){},status(n){this.statusCode=n;return this;},json(v){this.body=v;}};
  await require('../api/media-studio/public')({method:'GET',query:{token}},res);
  assert.equal(res.statusCode,200);assert.ok(!JSON.stringify(res.body).includes(a));assert.ok(!JSON.stringify(res.body).includes('storage_path'));
  await service.revoke(a,p.id,link.id);await assert.rejects(service.publicArtifact(token),{code:'not_found'});
  const second=await service.issueLink(a,p.id,build.id,'published'),secondToken=new URL(second.url).searchParams.get('token');
  await service.archive(a,p.id,true);assert.equal((await service.list(a)).length,0);assert.equal((await service.list(a,true)).length,1);
  await assert.rejects(service.publicArtifact(secondToken),{code:'not_found'});
  await service.archive(a,p.id,false);await assert.rejects(service.publicArtifact(secondToken),{code:'not_found'},'restoring never revives old links');
  assert.equal((await service.state(a,p.id)).versions.length,1);
  const preview=await service.issueLink(a,p.id,build.id,'preview'),previewToken=new URL(preview.url).searchParams.get('token');
  const real=Date.now();t.mock.method(Date,'now',()=>real+16*60000);
  await assert.rejects(service.publicArtifact(previewToken),{code:'not_found'});
  assert.ok(f.calls.every(c=>!c.path.includes('/rest/')));
});
test('same request from simultaneous tabs creates at most one job; run claims once',async t=>{
  fixture(t);const calls=providers(t),owner=uuid(),p=await service.create(owner,'test',{}),request=uuid();
  const queued=await Promise.allSettled(Array.from({length:6},()=>service.enqueue(owner,p.id,'build','สร้างเกม',request)));
  assert.equal(queued.filter(r=>r.status==='fulfilled').length,1);
  assert.ok(queued.filter(r=>r.status==='rejected').every(r=>r.reason.code==='workspace_busy'));
  const job=await service.enqueue(owner,p.id,'build','สร้างเกม',request);
  const runs=await Promise.all(Array.from({length:6},()=>service.run(owner,p.id,job.id)));
  assert.equal(runs.filter(r=>r.started).length,1);assert.equal(calls(),1);
});
test('teacher/global worker caps and expired claims do not automatically charge for retries',async t=>{
  fixture(t);const calls=providers(t),a=uuid(),b=uuid(),pa=await service.create(a,'a',{}),pb=await service.create(b,'b',{});
  const ja=await service.enqueue(a,pa.id,'build','สร้างเกม',uuid()),jb=await service.enqueue(b,pb.id,'build','สร้างเกม',uuid());
  const g0=await leases.acquire('global/0'),g1=await leases.acquire('global/1');
  assert.equal((await service.run(a,pa.id,ja.id)).started,false);assert.equal(calls(),0);
  await leases.release(g0);await leases.release(g1);
  const teacher=await leases.acquire(`teacher/${a}`);
  assert.equal((await service.run(a,pa.id,ja.id)).started,false);
  await service.run(b,pb.id,jb.id);assert.equal(calls(),1);await leases.release(teacher);
  await db.put(`users/${a}/claims/${pa.id}_${ja.id}.json`,{started_at:new Date(Date.now()-leases.TTL-1).toISOString(),expires:Date.now()-1});
  assert.equal((await service.state(a,pa.id)).jobs[0].error_code,'job_expired');
  assert.equal((await service.run(a,pa.id,ja.id)).started,false);assert.equal(calls(),1);
});
test('lost response after result commit reconciles success and preserves immutable artifact',async t=>{
  const f=fixture(t);const calls=providers(t),a=uuid(),p=await service.create(a,'test',{}),j=await service.enqueue(a,p.id,'build','สร้างเกม',uuid());
  f.failAfter=name=>name.includes('/results/build/');
  assert.equal((await service.run(a,p.id,j.id)).status,'succeeded');
  assert.equal((await service.state(a,p.id)).versions.length,1);
  await service.run(a,p.id,j.id);assert.equal(calls(),1);
  assert.ok([...f.objects.keys()].some(n=>n.includes('/artifacts/')));
});
test('Media Studio has no daily request budget while pending, version and project limits reject before AI calls',async t=>{
  fixture(t);const calls=providers(t),a=uuid(),p=await service.create(a,'test',{});
  const day=new Date(Date.now()+7*3600000).toISOString().slice(0,10);
  for(let i=0;i<40;i++)await db.put(`users/${a}/quota/${day}/${p.id}_${uuid()}.json`,{});
  assert.equal((await service.enqueue(a,p.id,'plan','โควตาที่บันทึกไว้ไม่ต้องจำกัด',uuid())).status,'queued');
  const b=uuid(),ps=[];for(let i=0;i<4;i++)ps.push(await service.create(b,`project ${i}`,{}));
  for(let i=0;i<3;i++)await service.enqueue(b,ps[i].id,'plan','รอทำงาน',uuid());
  await assert.rejects(service.enqueue(b,ps[3].id,'plan','งานที่สี่',uuid()),{code:'queue_limit'});
  const c=uuid(),pc=await service.create(c,'versions',{});
  for(let i=0;i<30;i++)await db.put(`users/${c}/results/build/${pc.id}_${uuid()}.json`,{version:{id:uuid()}});
  await assert.rejects(service.enqueue(c,pc.id,'build','ครบแล้ว',uuid()),{code:'version_limit'});
  for(let i=1;i<100;i++)await db.put(`users/${c}/projects/${uuid()}.json`,{});
  await assert.rejects(service.create(c,'เต็ม',{}),{code:'project_limit'});assert.equal(calls(),0);
});
test('archive during generation prevents publication; artifact integrity and review fail closed',async t=>{
  fixture(t);providers(t);const a=uuid(),p=await service.create(a,'test',{}),j=await service.enqueue(a,p.id,'build','สร้างเกม',uuid());
  t.mock.method(ai,'ask',async()=>{await service.archive(a,p.id,true);return sample;});
  assert.equal((await service.run(a,p.id,j.id)).error_code,'project_archived');
  assert.equal((await service.state(a,p.id)).versions.length,0);
  await service.archive(a,p.id,false);
  const version=uuid(),storage_path=`users/${a}/artifacts/${p.id}_${version}.json`;
  await db.put(storage_path,artifact.validateArtifact(sample));
  await db.put(`users/${a}/results/build/${p.id}_${version}.json`,{version:{id:version,project_id:p.id,storage_path,sha256:'0'.repeat(64),review:{browser_check:'passed',policy_version:artifact.POLICY_VERSION}}});
  const link=await service.issueLink(a,p.id,version,'published');
  await assert.rejects(service.publicArtifact(new URL(link.url).searchParams.get('token')),{code:'media_unavailable'});
  const unreviewed=uuid();await db.put(`users/${a}/results/build/${p.id}_${unreviewed}.json`,{version:{review:{browser_check:'failed'}}});
  await assert.rejects(service.issueLink(a,p.id,unreviewed,'published'),{code:'review_required'});
});
test('authenticated HTTP ignores forged owner fields and requires explicit teacher review',async t=>{
  const f=fixture(t);providers(t);const a=uuid(),b=uuid();f.sessions.set('Bearer teacher-a',a);
  // Exercise the protected workflow itself; production defaults to paused.
  const handlerPath=require.resolve('../api/media-studio'),previous=process.env.MEDIA_STUDIO_ENABLED;
  process.env.MEDIA_STUDIO_ENABLED='true';delete require.cache[handlerPath];
  const handler=require('../api/media-studio');
  t.after(()=>{if(previous===undefined)delete process.env.MEDIA_STUDIO_ENABLED;else process.env.MEDIA_STUDIO_ENABLED=previous;delete require.cache[handlerPath];});
  const call=async body=>{
    const res={setHeader(){},status(n){this.statusCode=n;return this;},json(v){this.body=v;}};
    await handler({method:'POST',headers:{host:'app.test',origin:'https://app.test',authorization:'Bearer teacher-a'},body},res);return res;
  };
  const created=await call({action:'create',teacher_id:b,title:'real owner',context:{classroom:'ม.1/1',subject:'วิทยาศาสตร์'}});
  assert.equal(created.statusCode,200);const p=created.body.project;
  assert.equal((await service.list(b)).length,0);assert.equal((await service.list(a)).length,1);
  assert.deepEqual(p.context,{subject:'',classroom:'',goal:'',duration_minutes:15},'Studio projects never bind a conversation to a classroom');
  const j=await service.enqueue(a,p.id,'build','สร้างเกม',uuid());await service.run(a,p.id,j.id);
  assert.equal((await call({action:'publish',project_id:p.id,version_id:j.id,reviewed:false})).statusCode,400);
  assert.equal((await call({action:'publish',project_id:p.id,version_id:j.id,reviewed:true})).statusCode,200);
  const other=await service.create(b,'other',{});
  assert.equal((await call({action:'archive',project_id:other.id,archived:true,teacher_id:b})).statusCode,404);
  assert.equal((await call({action:'create',title:'x'.repeat(33000)})).statusCode,413);
});
