const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const elements = new Map();
const c = { id:'room',subject:'วิทยาศาสตร์',className:'ม.1/1',academicYear:2569,students:[{id:'a',name:'A "<script>',no:1},{id:'b',name:'B',no:2}],attendance:{'2026-01-01':{a:'present'},'2026-05-10':{a:'present',b:'absent'},'2026-05-11':{a:'leave'},'2027-01-01':{a:'present'}},scores:{config:{ratio:{before:100,after:0,mid:0,final:0}},items:[{id:'work',name:'งาน',max:10,bucket:'before'}],marks:{work:{a:0,b:''}},gradeOverride:{}}};
let saves=0;
let timerId = 0;
const timers = new Map();
const context=vm.createContext({console,appState:{classes:[c],teacherName:'Teacher'},window:{},document:{querySelector(){return null;},getElementById(id){if(!elements.has(id))elements.set(id,{innerHTML:'',classList:{remove(){}}});return elements.get(id);}},getTodayString:()=> '2026-09-08',saveState:()=>saves++,showToast(){},setTimeout(fn){const id=++timerId;timers.set(id,fn);return id;},clearTimeout(id){timers.delete(id);}});
for(const file of ['scores.js','pp5.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../js',file),'utf8'),context);
vm.runInContext("scoreCurrentClassId='room'",context);
const cfg=context.pp5Config(c);
cfg.start='2026-05-01';cfg.end='2026-09-30';
assert.equal(context.pp5StudentResult(c,c.students[0]).grade,'0','recorded zero is a complete grade');
assert.equal(context.pp5StudentResult(c,c.students[1]).grade,'ยังไม่ครบ','blank is not a failing grade');
assert.equal(context.pp5Dates(c).length,2,'term range excludes other dates and future records');
const attendance=context.pp5Attendance(c,'b',context.pp5Dates(c));
assert.equal(attendance.absent,1);assert.equal(attendance.missing,1);
c.scores.config.ratio.before=50;c.scores.config.ratio.final=50;
assert.equal(context.pp5StudentResult(c,c.students[0]).complete,false,'missing weighted exam bucket prevents final grade');
c.scores.config.ratio.before=100;c.scores.config.ratio.final=0;
const traitInputsA=['3','3','3','3','3','2','2','2'].map((value,n)=>({dataset:{student:'a',field:`trait${n}`},value}));
context.pp5SaveAssessment({querySelectorAll:selector=>selector==='[data-student]'?[...traitInputsA,{dataset:{student:'a',field:'reading'},value:'3'},{dataset:{student:'a',field:'remark'},value:'"<img onerror=alert(1)>'}]:[]});
assert.equal(saves,1);assert.equal(cfg.assessments.a.traits,'3','5 excellent traits and none below good summarize as excellent');
assert.equal(context.pp5TraitSummary({trait0:'3',trait1:'3',trait2:'2',trait3:'2',trait4:'2',trait5:'1',trait6:'1',trait7:'1'}),'2','5 traits at good or better summarize as good');
assert.equal(context.pp5TraitSummary({trait0:'3',trait1:'2',trait2:'1',trait3:'1',trait4:'1',trait5:'1',trait6:'1',trait7:'1'}),'1','all passing but only 2 good-or-better traits summarize as pass');
assert.equal(context.pp5TraitSummary({trait0:'3',trait1:'3',trait2:'3',trait3:'3',trait4:'3',trait5:'3',trait6:'3',trait7:'0'}),'0','one failed trait makes the summary fail');
assert.equal(context.pp5TraitSummary({trait0:'3',trait1:'3'}),'','incomplete 8-trait evidence is not summarized');
const traitInputsB=['2','2','2','2','2','1','1','1'].map((value,n)=>({dataset:{student:'b',field:`trait${n}`},value}));
const autosaveForm={querySelectorAll(selector){return selector==='[data-student]'?[...traitInputsB,{dataset:{student:'b',field:'reading'},value:'1'}]:selector==='[data-summary-student]'?[{dataset:{summaryStudent:'b'},textContent:''}]:[];},querySelector(){return null;}};
const changedSelect={dataset:{student:'b',field:'trait0'},value:'2',form:autosaveForm,classList:{remove(){},add(){}}};
context.pp5AssessmentSelectChanged(changedSelect);
assert.equal(cfg.assessments.b?.traits,undefined,'autosave waits briefly while the teacher is still editing');
for(const fn of timers.values())fn();
timers.clear();
assert.equal(cfg.assessments.b.traits,'2','changed assessment select derives the trait summary used by reports');
assert.equal(cfg.assessments.b.reading,'1','autosave writes the whole visible assessment form');
cfg.assessments.a.reading='2';
cfg.assessments.b.reading='';
const bulkForm={elements:{pp5BulkMode:{value:'blank'}},querySelectorAll(){return [];},querySelector(){return null;}};
context.pp5ApplyAssessmentBulk(bulkForm,'reading','3');
assert.equal(cfg.assessments.a.reading,'2','blank-only bulk fill does not overwrite an existing assessment');
assert.equal(cfg.assessments.b.reading,'3','blank-only bulk fill updates empty cells for many students');
context.pp5Select('assessment');
context.document.querySelector=()=>autosaveForm;
autosaveForm.querySelectorAll=selector=>selector==='[data-student]'?[...['3','3','3','3','3','2','2','2'].map((value,n)=>({dataset:{student:'b',field:`trait${n}`},value})),{dataset:{student:'b',field:'reading'},value:'3'}]:selector==='[data-summary-student]'?[{dataset:{summaryStudent:'b'},textContent:''}]:[];
context.pp5Select('summary');
assert.equal(cfg.assessments.b.traits,'3','switching to the report flushes the latest visible form values first');
assert.equal(cfg.assessments.b.reading,'3');
context.document.querySelector=()=>null;
let html=context.pp5Document(c,'all');
assert.ok(html.includes('ไม่ผ่าน'));assert.ok(html.includes('ยังไม่ครบ'));
assert.ok(html.includes('&quot;&lt;img'));assert.ok(!html.includes('<script>'));
assert.equal(context.pp5DataSheets(c).filter(s=>s.section==='attendance').length,2);
context.renderPp5(c);assert.ok(elements.get('web-scores-matrix-wrap').innerHTML.includes('pp5-workspace'));
context.pp5Select('assessment');assert.ok(elements.get('web-scores-matrix-wrap').innerHTML.includes('pp5SaveAssessment'));
assert.ok(elements.get('web-scores-matrix-wrap').innerHTML.includes('กรอกเร็วหลายคน'));
assert.ok(elements.get('web-scores-matrix-wrap').innerHTML.includes('pp5-entry-table'));
assert.ok(elements.get('web-scores-matrix-wrap').innerHTML.includes('data-field="trait0"'));
assert.ok(!elements.get('web-scores-matrix-wrap').innerHTML.includes('pp5-inline-tools'));
assert.ok(!elements.get('web-scores-matrix-wrap').innerHTML.includes('pp5-editable-document'));
let summary=context.pp5Summary(c);
assert.equal(summary.total,2);
assert.equal(summary.completed,1);
assert.equal(summary.pending[0].student.id,'b');
const gradeCounts=summary.sheets[0];
assert.equal(gradeCounts.rows[0][gradeCounts.headers.indexOf('0')],1,'recorded zero is counted as grade zero');
assert.equal(gradeCounts.rows[0][gradeCounts.headers.indexOf('ยังไม่ครบ')],1,'blank scores remain incomplete');
assert.equal(gradeCounts.rows[1][gradeCounts.headers.indexOf('0')],50,'percent denominator is the entire classroom');
for(const sheet of summary.sheets)assert.equal(sheet.rows[0].slice(1).reduce((a,b)=>a+b,0),2,'every student belongs to exactly one category');
c.scores.gradeOverride.b='ร';
summary=context.pp5Summary(c);
assert.equal(summary.sheets[0].rows[0][summary.sheets[0].headers.indexOf('ร')],1,'explicit special status is preserved with missing scores');
assert.equal(summary.pending.length,1,'special status does not hide missing information');
delete c.scores.gradeOverride.b;
cfg.province='เชียงราย';
html=context.pp5Document(c,'summary');
assert.ok(html.includes('แบบบันทึกผลการเรียนประจำรายวิชา'));
assert.ok(html.includes('เชียงราย'));
assert.ok(!html.includes('ClassKru'));
assert.ok(html.includes('รายชื่อนักเรียนที่ข้อมูลยังไม่ครบ'));
assert.ok(!html.includes('<script>'));
assert.equal(context.pp5DataSheets(c).find(s=>s.title==='สรุปผลการเรียน').rows[1][8],50,'Excel uses the same numeric percentages');
c.students=Array.from({length:40},(_,i)=>({id:`s${i}`,name:`นักเรียน ${i}`}));
html=context.pp5Document(c,'scores');assert.equal((html.match(/class="pp5-page"/g)||[]).length,6,'summary and item tables split into 18-student pages');
c.students=[];c.scores.items=[];assert.doesNotThrow(()=>context.pp5Document(c,'all'));
summary=context.pp5Summary(c);
assert.equal(summary.completed,0);
assert.ok(summary.sheets.every(sheet=>sheet.rows[1].slice(1).every(value=>value==='—')),'empty classroom has no invented percentages');
console.log('PP5 data, pagination, missing marks, assessments and escaping tests passed');
