const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const elements = new Map();
const c = { id:'room',subject:'วิทยาศาสตร์',className:'ม.1/1',academicYear:2569,students:[{id:'a',name:'A "<script>',no:1},{id:'b',name:'B',no:2}],attendance:{'2026-01-01':{a:'present'},'2026-05-10':{a:'present',b:'absent'},'2026-05-11':{a:'leave'},'2027-01-01':{a:'present'}},scores:{config:{ratio:{before:100,after:0,mid:0,final:0}},items:[{id:'work',name:'งาน',max:10,bucket:'before'}],marks:{work:{a:0,b:''}},gradeOverride:{}}};
let saves=0;
const context=vm.createContext({console,appState:{classes:[c],teacherName:'Teacher'},window:{},document:{getElementById(id){if(!elements.has(id))elements.set(id,{innerHTML:'',classList:{remove(){}}});return elements.get(id);}},getTodayString:()=> '2026-09-08',saveState:()=>saves++,showToast(){}});
for(const file of ['scores.js','pp5.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../js',file),'utf8'),context);
vm.runInContext("scoreCurrentClassId='room'",context);
const cfg=context.pp5Config(c);
cfg.start='2026-05-01';cfg.end='2026-09-30';
assert.equal(context.pp5StudentResult(c,c.students[0]).grade,'0','recorded zero is a complete grade');
assert.equal(context.pp5StudentResult(c,c.students[1]).grade,'ยังไม่ครบ','blank is not a failing grade');
assert.equal(context.pp5Dates(c).length,2,'term range excludes other dates and future records');
const attendance=context.pp5Attendance(c,'b',context.pp5Dates(c));
assert.equal(attendance.absent,1);assert.equal(attendance.missing,1);
c.scores.config.ratio.before=50;c.scores.config.ratio.final=50;
assert.equal(context.pp5StudentResult(c,c.students[0]).complete,false,'missing weighted exam bucket prevents final grade');
c.scores.config.ratio.before=100;c.scores.config.ratio.final=0;
context.pp5SaveAssessment({querySelectorAll:()=>[{dataset:{student:'a',field:'traits'},value:'0'},{dataset:{student:'a',field:'reading'},value:'3'},{dataset:{student:'a',field:'remark'},value:'"<img onerror=alert(1)>'}]});
assert.equal(saves,1);assert.equal(cfg.assessments.a.traits,'0');
let html=context.pp5Document(c,'all');
assert.ok(html.includes('ไม่ผ่าน'));assert.ok(html.includes('ยังไม่ครบ'));
assert.ok(html.includes('&quot;&lt;img'));assert.ok(!html.includes('<script>'));
assert.equal(context.pp5DataSheets(c).filter(s=>s.section==='attendance').length,2);
context.renderPp5(c);assert.ok(elements.get('web-scores-matrix-wrap').innerHTML.includes('pp5-workspace'));
context.pp5Select('assessment');assert.ok(elements.get('web-scores-matrix-wrap').innerHTML.includes('pp5SaveAssessment'));
let summary=context.pp5Summary(c);
assert.equal(summary.total,2);
assert.equal(summary.completed,1);
assert.equal(summary.pending[0].student.id,'b');
const gradeCounts=summary.sheets[0];
assert.equal(gradeCounts.rows[0][gradeCounts.headers.indexOf('0')],1,'recorded zero is counted as grade zero');
assert.equal(gradeCounts.rows[0][gradeCounts.headers.indexOf('ยังไม่ครบ')],1,'blank scores remain incomplete');
assert.equal(gradeCounts.rows[1][gradeCounts.headers.indexOf('0')],50,'percent denominator is the entire classroom');
for(const sheet of summary.sheets)assert.equal(sheet.rows[0].slice(1).reduce((a,b)=>a+b,0),2,'every student belongs to exactly one category');
c.scores.gradeOverride.b='ร';
summary=context.pp5Summary(c);
assert.equal(summary.sheets[0].rows[0][summary.sheets[0].headers.indexOf('ร')],1,'explicit special status is preserved with missing scores');
assert.equal(summary.pending.length,1,'special status does not hide missing information');
delete c.scores.gradeOverride.b;
cfg.province='เชียงราย';
html=context.pp5Document(c,'summary');
assert.ok(html.includes('แบบบันทึกผลการเรียนประจำรายวิชา'));
assert.ok(html.includes('เชียงราย'));
assert.ok(html.includes('รายชื่อนักเรียนที่ข้อมูลยังไม่ครบ'));
assert.ok(!html.includes('<script>'));
assert.equal(context.pp5DataSheets(c).find(s=>s.title==='สรุปผลการเรียน').rows[1][8],50,'Excel uses the same numeric percentages');
c.students=Array.from({length:40},(_,i)=>({id:`s${i}`,name:`นักเรียน ${i}`}));
html=context.pp5Document(c,'scores');assert.equal((html.match(/class="pp5-page"/g)||[]).length,6,'summary and item tables split into 18-student pages');
c.students=[];c.scores.items=[];assert.doesNotThrow(()=>context.pp5Document(c,'all'));
summary=context.pp5Summary(c);
assert.equal(summary.completed,0);
assert.ok(summary.sheets.every(sheet=>sheet.rows[1].slice(1).every(value=>value==='—')),'empty classroom has no invented percentages');
console.log('PP5 data, pagination, missing marks, assessments and escaping tests passed');
