'use strict';

const { Document, Packer, Paragraph, TextRun, AlignmentType, LevelFormat } = require('docx');
const { sendJson, parseBody, requestOriginIsValid } = require('../_lib/http');
const SUPABASE_URL = process.env.SUPABASE_URL || 'https://dzntiiuyqvkaxqpqzxeh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_SePLBF-dsJfx5T6Yvvcuew_vntSr3Vc';
const BODY_SIZE = 28; const TITLE_SIZE = 36;
const clean = (value, max = 1800) => String(value || '').trim().slice(0, max);
const asList = (value, maxItems = 18) => (Array.isArray(value) ? value : []).map(item => clean(item)).filter(Boolean).slice(0, maxItems);
async function authenticatedUser(req) { const token = String(req.headers.authorization || '').replace(/^Bearer\s+/i, ''); if (!token) return null; const response = await fetch(`${SUPABASE_URL}/auth/v1/user`, { headers:{ apikey:SUPABASE_PUBLISHABLE_KEY, Authorization:`Bearer ${token}` } }); return response.ok ? response.json() : null; }
function paragraph(text, options = {}) { return new Paragraph({ ...options, children:[new TextRun({ text:clean(text), font:'TH SarabunPSK', size:options.size || BODY_SIZE, bold:Boolean(options.bold) })] }); }
function sectionBlocks(title, values) { const list = asList(values); return [paragraph(title, { bold:true, spacing:{ before:170, after:60 } }), ...(list.length ? list.map(item => new Paragraph({ numbering:{ reference:'worksheet-bullets', level:0 }, children:[new TextRun({ text:item, font:'TH SarabunPSK', size:BODY_SIZE })] })) : [paragraph('........................................................................................................................', { spacing:{ after:50 } })])]; }
module.exports = async function handler(req, res) {
  if (req.method !== 'POST') return sendJson(res, 405, { error:'method_not_allowed' });
  if (!requestOriginIsValid(req)) return sendJson(res, 403, { error:'invalid_origin' });
  try {
    const user = await authenticatedUser(req); if (!user?.id) return sendJson(res, 401, { error:'authentication_required', message:'กรุณาเข้าสู่ระบบใหม่ก่อนส่งออกเอกสาร' });
    const worksheet = parseBody(req).worksheet || {}; const data = worksheet.worksheet && typeof worksheet.worksheet === 'object' ? worksheet.worksheet : worksheet; const title = clean(data.title || worksheet.title, 240);
    if (!title) return sendJson(res, 400, { error:'invalid_worksheet', message:'ไม่พบข้อมูลใบงานสำหรับส่งออก' });
    const indicators = Array.isArray(worksheet.indicators) ? worksheet.indicators.slice(0,18).map(item => `${clean(item.code,80)} ${clean(item.text,1000)}`.trim()).filter(Boolean) : [];
    const document = new Document({ styles:{ default:{ document:{ run:{ font:'TH SarabunPSK', size:BODY_SIZE } } } }, numbering:{ config:[{ reference:'worksheet-bullets', levels:[{ level:0, format:LevelFormat.BULLET, text:'•', alignment:AlignmentType.LEFT, style:{ paragraph:{ indent:{ left:520, hanging:260 }, spacing:{ after:35 } }, run:{ font:'TH SarabunPSK', size:BODY_SIZE } } }] }] }, sections:[{ properties:{ page:{ size:{ width:11906, height:16838 }, margin:{ top:1134, right:1134, bottom:1134, left:1134 } } }, children:[paragraph('ใบงาน', { size:TITLE_SIZE, bold:true, alignment:AlignmentType.CENTER, spacing:{ after:80 } }), paragraph(title, { size:32, bold:true, alignment:AlignmentType.CENTER, spacing:{ after:170 } }), paragraph(`วิชา ${clean(worksheet.subject,180) || '................................'}    ระดับชั้น ${clean(worksheet.grade,80) || '................................'}`, { spacing:{ after:35 } }), paragraph(`ห้องเรียน ${clean(worksheet.classLabel,220) || '................................'}    เวลา ${clean(worksheet.duration,80) || '................................'}`, { spacing:{ after:35 } }), paragraph(`ชื่อ-สกุล ........................................................................ เลขที่ ............`, { spacing:{ after:100 } }), ...sectionBlocks('ตัวชี้วัด / ผลการเรียนรู้', indicators), ...sectionBlocks('คำชี้แจง', data.directions), ...sectionBlocks('สถานการณ์หรือโจทย์กิจกรรม', data.context), ...sectionBlocks('ขั้นตอนการทำงาน', data.steps), ...sectionBlocks('ภารกิจ / คำถามชี้นำ', data.tasks), ...sectionBlocks('สิ่งที่นักเรียนต้องทำหรือบันทึก', data.responseAreas), ...sectionBlocks('ชิ้นงานที่ต้องส่ง', data.submission), ...sectionBlocks('เกณฑ์หรือแนวทางประเมินสำหรับครู', data.assessmentCriteria) ] }] });
    const buffer = await Packer.toBuffer(document); const fileName = encodeURIComponent(`${title}.docx`); res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.wordprocessingml.document'); res.setHeader('Content-Disposition', `attachment; filename="worksheet.docx"; filename*=UTF-8''${fileName}`); res.setHeader('Cache-Control','no-store, private'); return res.status(200).send(buffer);
  } catch (error) { console.error('Worksheet docx export error:', error); return sendJson(res, 500, { error:'export_failed', message:'เกิดข้อผิดพลาดขณะสร้างไฟล์ Word' }); }
};
