"use strict";

const wordData = `
CAT|animals|สัตว์|สัตว์เลี้ยงที่ชอบจับหนู|แมว|The cat is sleeping on the chair.|easy
DOG|animals|สัตว์|สัตว์เลี้ยงที่ซื่อสัตย์|สุนัข|The dog runs in the park.|easy
FROG|animals|สัตว์|สัตว์สีเขียวที่กระโดดได้|กบ|A frog lives near water.|easy
LION|animals|สัตว์|ราชาแห่งป่า|สิงโต|The lion has a loud roar.|easy
WHALE|animals|สัตว์|สัตว์ทะเลตัวใหญ่มาก|วาฬ|The whale swims in the ocean.|easy
GIRAFFE|animals|สัตว์|สัตว์ที่มีคอยาว|ยีราฟ|A giraffe has a very long neck.|medium
DOLPHIN|animals|สัตว์|สัตว์ทะเลที่ฉลาดและกระโดดเก่ง|โลมา|The dolphin jumps out of the water.|medium
PENGUIN|animals|สัตว์|นกที่บินไม่ได้และอยู่ในที่หนาว|เพนกวิน|A penguin walks on the ice.|medium
RABBIT|animals|สัตว์|สัตว์หูยาวที่ชอบแครอท|กระต่าย|The rabbit eats a carrot.|medium
ELEPHANT|animals|สัตว์|สัตว์บกที่มีงวงยาว|ช้าง|An elephant has a long trunk.|hard
RICE|food|อาหาร|อาหารหลักเม็ดเล็กที่หุงสุก|ข้าว|Rice is a common food in Thailand.|easy
CAKE|food|อาหาร|ของหวานอบสำหรับงานฉลอง|เค้ก|The cake has candles on top.|easy
SOUP|food|อาหาร|อาหารเหลวที่กินอุ่น ๆ|ซุป|The soup is hot and tasty.|easy
BREAD|food|อาหาร|อาหารอบจากแป้ง|ขนมปัง|Bread is fresh from the oven.|easy
APPLE|food|อาหาร|ผลไม้ที่มีสีแดงหรือเขียว|แอปเปิล|An apple is on the table.|easy
NOODLES|food|อาหาร|เส้นอาหารยอดนิยม|ก๋วยเตี๋ยว|Noodles are delicious with soup.|medium
SANDWICH|food|อาหาร|ขนมปังสองแผ่นมีไส้ตรงกลาง|แซนด์วิช|I eat a sandwich for lunch.|medium
AVOCADO|food|อาหาร|ผลไม้เนื้อนุ่มสีเขียว|อะโวคาโด|Avocado is creamy and green.|medium
CHEESE|food|อาหาร|ผลิตภัณฑ์จากนมรสเค็ม|ชีส|Cheese melts on hot pizza.|medium
CHOCOLATE|food|อาหาร|ขนมหวานสีน้ำตาลจากโกโก้|ช็อกโกแลต|Chocolate tastes sweet.|hard
PEN|school|โรงเรียน|อุปกรณ์สำหรับเขียนด้วยหมึก|ปากกา|My pen is blue.|easy
BOOK|school|โรงเรียน|สิ่งที่ใช้สำหรับอ่าน|หนังสือ|This book has many pictures.|easy
DESK|school|โรงเรียน|โต๊ะสำหรับนั่งเรียน|โต๊ะเรียน|My desk is near the window.|easy
CLASS|school|โรงเรียน|กลุ่มนักเรียนที่เรียนด้วยกัน|ชั้นเรียน|Our class starts at eight.|easy
RULER|school|โรงเรียน|อุปกรณ์สำหรับวัดเส้นตรง|ไม้บรรทัด|Use a ruler to draw a line.|easy
LESSON|school|โรงเรียน|เนื้อหาที่ครูสอนในหนึ่งคาบ|บทเรียน|Today's lesson is fun.|medium
SCHOOL|school|โรงเรียน|สถานที่สำหรับเรียนหนังสือ|โรงเรียน|The school has a big library.|medium
PENCIL|school|โรงเรียน|อุปกรณ์เขียนที่ลบได้|ดินสอ|My pencil is sharp.|medium
ERASER|school|โรงเรียน|อุปกรณ์สำหรับลบรอยดินสอ|ยางลบ|The eraser is pink.|medium
NOTEBOOK|school|โรงเรียน|สมุดสำหรับจดบันทึก|สมุดโน้ต|Write your ideas in a notebook.|hard
CHEF|jobs|อาชีพ|ผู้ทำอาหารในครัว|เชฟ|The chef cooks a meal.|easy
NURSE|jobs|อาชีพ|ผู้ดูแลผู้ป่วยในโรงพยาบาล|พยาบาล|The nurse helps the patient.|easy
PILOT|jobs|อาชีพ|ผู้ขับเครื่องบิน|นักบิน|The pilot flies the plane.|easy
ACTOR|jobs|อาชีพ|ผู้แสดงในภาพยนตร์หรือละคร|นักแสดง|The actor is in a movie.|easy
JUDGE|jobs|อาชีพ|ผู้ตัดสินการแข่งขันหรือคดี|ผู้ตัดสิน|The judge makes a fair decision.|easy
DOCTOR|jobs|อาชีพ|ผู้รักษาคนป่วย|แพทย์|The doctor checks my health.|medium
SINGER|jobs|อาชีพ|ผู้ร้องเพลง|นักร้อง|The singer has a beautiful voice.|medium
DRIVER|jobs|อาชีพ|ผู้ขับยานพาหนะ|คนขับรถ|The driver stops the bus.|medium
TEACHER|jobs|อาชีพ|ผู้สอนนักเรียน|ครู|The teacher explains the lesson.|medium
FIREFIGHTER|jobs|อาชีพ|ผู้ดับเพลิงและช่วยเหลือเหตุฉุกเฉิน|นักผจญเพลิง|A firefighter puts out fires.|hard
ATOM|science|วิทยาศาสตร์|หน่วยเล็กมากที่ประกอบเป็นสสาร|อะตอม|An atom is very small.|easy
STAR|science|วิทยาศาสตร์|วัตถุสว่างบนท้องฟ้ายามคืน|ดาวฤกษ์|A star shines at night.|easy
MOON|science|วิทยาศาสตร์|บริวารธรรมชาติของโลก|ดวงจันทร์|The moon moves around Earth.|easy
PLANT|science|วิทยาศาสตร์|สิ่งมีชีวิตที่สร้างอาหารด้วยแสง|พืช|A plant needs water and light.|easy
LIGHT|science|วิทยาศาสตร์|พลังงานที่ทำให้เรามองเห็น|แสง|Light travels very fast.|easy
PLANET|science|วิทยาศาสตร์|วัตถุขนาดใหญ่ที่โคจรรอบดาวฤกษ์|ดาวเคราะห์|Earth is a planet.|medium
ENERGY|science|วิทยาศาสตร์|ความสามารถในการทำงาน|พลังงาน|Food gives us energy.|medium
MATTER|science|วิทยาศาสตร์|สิ่งที่มีมวลและกินที่ว่าง|สสาร|Matter can be solid or liquid.|medium
OXYGEN|science|วิทยาศาสตร์|ก๊าซที่มนุษย์ใช้หายใจ|ออกซิเจน|We need oxygen to breathe.|medium
TELESCOPE|science|วิทยาศาสตร์|เครื่องมือสำหรับมองวัตถุไกลในอวกาศ|กล้องโทรทรรศน์|A telescope helps us see stars.|hard`
  .trim().split("\n").map(row => { const [word,category,categoryName,hint,translation,example,difficulty] = row.split("|"); return {word,category,categoryName,hint,translation,example,difficulty}; });

const gameState = {currentWord:null,guessedLetters:new Set(),wrongLetters:new Set(),mistakes:0,maxMistakes:6,score:0,roundScore:0,letterScore:0,streak:0,hintUsed:false,gameActive:false,selectedCategory:"animals",selectedDifficulty:"easy",timeRemaining:0,timerId:null,roundNumber:0,soundEnabled:true,playedCurrentRound:false};
const keys = {highScore:"wordRocket_highScore",gamesPlayed:"wordRocket_gamesPlayed",gamesWon:"wordRocket_gamesWon",bestStreak:"wordRocket_bestStreak",sound:"wordRocket_soundEnabled",category:"wordRocket_lastCategory",difficulty:"wordRocket_lastDifficulty"};
const elements = {}; let audioContext; let noticeTimer;

function cacheDOMElements() { ["sound-button","stats-button","new-game-button","category-value","difficulty-value","score-value","streak-value","energy-value","round-value","timer-card","timer-value","mission-status","rocket","rocket-note","countdown","hint-value","hint-button","word-display","wrong-letters","letter-keyboard","start-modal","category-options","difficulty-options","start-button","start-error","result-modal","result-icon","result-title","result-subtitle","result-word","result-translation","result-example","score-breakdown","retry-button","next-button","choose-button","stats-modal","close-stats-button","reset-stats-button","high-score-stat","games-played-stat","games-won-stat","win-rate-stat","best-streak-stat","notification","score-float"].forEach(id => elements[id] = document.getElementById(id)); }
function getStorage(key,fallback) { try { const value = localStorage.getItem(key); return value === null ? fallback : value; } catch { return fallback; } }
function setStorage(key,value) { try { localStorage.setItem(key,String(value)); } catch { /* Local storage may be unavailable. */ } }
function number(value) { const result = Number(value); return Number.isFinite(result) && result >= 0 ? result : 0; }
function getStats() { return {highScore:number(getStorage(keys.highScore,0)),gamesPlayed:number(getStorage(keys.gamesPlayed,0)),gamesWon:number(getStorage(keys.gamesWon,0)),bestStreak:number(getStorage(keys.bestStreak,0))}; }
function loadStats() { gameState.soundEnabled = getStorage(keys.sound,"true") !== "false"; const category = getStorage(keys.category,"animals"); const difficulty = getStorage(keys.difficulty,"easy"); gameState.selectedCategory = wordData.some(item => item.category === category) ? category : "animals"; gameState.selectedDifficulty = ["easy","medium","hard"].includes(difficulty) ? difficulty : "easy"; updateSoundButton(); }
function saveStats(won) { if (gameState.playedCurrentRound) return; const stats = getStats(); stats.gamesPlayed += 1; stats.gamesWon += won ? 1 : 0; stats.highScore = Math.max(stats.highScore,gameState.score); stats.bestStreak = Math.max(stats.bestStreak,gameState.streak); setStorage(keys.gamesPlayed,stats.gamesPlayed); setStorage(keys.gamesWon,stats.gamesWon); setStorage(keys.highScore,stats.highScore); setStorage(keys.bestStreak,stats.bestStreak); gameState.playedCurrentRound = true; }
function resetStats() { if (!window.confirm("ต้องการล้างสถิติทั้งหมดในอุปกรณ์นี้ใช่หรือไม่?")) return; [keys.highScore,keys.gamesPlayed,keys.gamesWon,keys.bestStreak].forEach(key => { try { localStorage.removeItem(key); } catch { /* Ignore. */ } }); showStatsModal(); showNotification("ล้างสถิติแล้ว"); }

function bindEvents() {
  elements["category-options"].addEventListener("click",event => { const button = event.target.closest("button[data-category]"); if (button) { gameState.selectedCategory = button.dataset.category; updateSelections(); } });
  elements["difficulty-options"].addEventListener("click",event => { const button = event.target.closest("button[data-difficulty]"); if (button) { gameState.selectedDifficulty = button.dataset.difficulty; updateSelections(); } });
  elements["start-button"].addEventListener("click",() => startNewGame(true)); elements["new-game-button"].addEventListener("click",openStartModal); elements["hint-button"].addEventListener("click",useHint); elements["sound-button"].addEventListener("click",toggleSound); elements["stats-button"].addEventListener("click",showStatsModal); elements["close-stats-button"].addEventListener("click",closeStatsModal); elements["reset-stats-button"].addEventListener("click",resetStats);
  elements["retry-button"].addEventListener("click",() => { closeResultModal(); resetRound(gameState.currentWord); }); elements["next-button"].addEventListener("click",() => { closeResultModal(); playNextWord(); }); elements["choose-button"].addEventListener("click",() => { closeResultModal(); openStartModal(); });
  elements["letter-keyboard"].addEventListener("click",event => { const button = event.target.closest("button[data-letter]"); if (button) handleLetterGuess(button.dataset.letter); });
  document.addEventListener("keydown",event => { const letter = event.key.toUpperCase(); if (gameState.gameActive && /^[A-Z]$/.test(letter)) handleLetterGuess(letter); });
  [elements["result-modal"],elements["stats-modal"]].forEach(modal => modal.addEventListener("click",event => { if (event.target === modal) modal.classList.remove("is-open"); }));
}
function updateSelections() { elements["category-options"].querySelectorAll("button").forEach(button => button.classList.toggle("selected",button.dataset.category === gameState.selectedCategory)); elements["difficulty-options"].querySelectorAll("button").forEach(button => button.classList.toggle("selected",button.dataset.difficulty === gameState.selectedDifficulty)); }
function openStartModal() { stopTimer(); gameState.gameActive = false; elements["start-error"].textContent = ""; updateSelections(); elements["start-modal"].classList.add("is-open"); }
function closeStartModal() { elements["start-modal"].classList.remove("is-open"); }
function availableWords() { return wordData.filter(item => item.category === gameState.selectedCategory && item.difficulty === gameState.selectedDifficulty); }
function startNewGame(resetSession) { const choices = availableWords(); if (!choices.length) { elements["start-error"].textContent = "ยังไม่มีคำศัพท์สำหรับตัวเลือกนี้ กรุณาเลือกใหม่"; return; } setStorage(keys.category,gameState.selectedCategory); setStorage(keys.difficulty,gameState.selectedDifficulty); if (resetSession) { gameState.score = 0; gameState.streak = 0; gameState.roundNumber = 0; } closeStartModal(); playNextWord(); }
function selectRandomWord() { const choices = availableWords(); const different = choices.filter(item => !gameState.currentWord || item.word !== gameState.currentWord.word); const pool = different.length ? different : choices; return pool[Math.floor(Math.random() * pool.length)] || null; }
function playNextWord() { const word = selectRandomWord(); if (!word) { showNotification("ไม่พบคำศัพท์สำหรับตัวเลือกนี้"); return openStartModal(); } gameState.roundNumber += 1; resetRound(word); }
function resetRound(word) { stopTimer(); gameState.currentWord = word; gameState.guessedLetters = new Set(); gameState.wrongLetters = new Set(); gameState.mistakes = 0; gameState.maxMistakes = gameState.selectedDifficulty === "hard" ? 5 : 6; gameState.roundScore = 0; gameState.letterScore = 0; gameState.hintUsed = false; gameState.gameActive = true; gameState.playedCurrentRound = false; gameState.timeRemaining = gameState.selectedDifficulty === "hard" ? 60 : 0; elements["rocket"].className = "rocket rocket-state-0"; elements["countdown"].textContent = ""; elements["mission-status"].textContent = "ภารกิจเริ่มแล้ว เลือกตัวอักษรให้ถูกต้อง!"; elements["rocket-note"].textContent = "ระบบทั้งหมดทำงานปกติ"; elements["hint-value"].textContent = word.hint; elements["hint-button"].disabled = false; createKeyboard(); updateWordDisplay(); updateGameStatus(); if (gameState.selectedDifficulty === "hard") startTimer(); }
function createKeyboard() { elements["letter-keyboard"].innerHTML = ""; "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").forEach(letter => { const button = document.createElement("button"); button.type = "button"; button.className = "letter-button"; button.dataset.letter = letter; button.textContent = letter; button.setAttribute("aria-label",`ทายตัวอักษร ${letter}`); elements["letter-keyboard"].append(button); }); }
function handleLetterGuess(letter) { if (!gameState.gameActive || gameState.guessedLetters.has(letter) || gameState.wrongLetters.has(letter)) return; const correct = gameState.currentWord.word.includes(letter); if (correct) { gameState.guessedLetters.add(letter); const points = [...gameState.currentWord.word].filter(character => character === letter).length * 10; gameState.letterScore += points; gameState.roundScore += points; gameState.score += points; updateKeyboardButton(letter,true); updateWordDisplay(); showScoreFloat(`+${points}`); playSound("correct"); if (checkWin()) completeMission(); } else { gameState.wrongLetters.add(letter); gameState.mistakes += 1; updateKeyboardButton(letter,false); updateRocketState(); playSound("wrong"); if (checkLoss()) failMission("ใช้พลังงานหมดแล้ว"); } updateGameStatus(); }
function updateKeyboardButton(letter,correct) { const button = elements["letter-keyboard"].querySelector(`[data-letter="${letter}"]`); if (!button) return; button.disabled = true; button.classList.add(correct ? "letter-correct" : "letter-wrong"); button.setAttribute("aria-label",`${letter}: ${correct ? "ถูกต้อง" : "ไม่ถูกต้อง"}`); }
function updateWordDisplay() { const word = gameState.currentWord ? gameState.currentWord.word : ""; elements["word-display"].innerHTML = ""; [...word].forEach(letter => { const slot = document.createElement("span"); const revealed = gameState.guessedLetters.has(letter); slot.className = `letter-slot${revealed ? " revealed" : ""}`; slot.textContent = revealed ? letter : "_"; slot.setAttribute("aria-label",revealed ? `ตัวอักษร ${letter}` : "ตัวอักษรที่ยังไม่เปิด"); elements["word-display"].append(slot); }); elements["wrong-letters"].textContent = `ตัวอักษรที่พลาด: ${[...gameState.wrongLetters].join(" · ") || "—"}`; }
function updateRocketState() { const notes = ["ระบบทั้งหมดทำงานปกติ","พลังงานลดลงเล็กน้อย","เปลวไฟเริ่มอ่อนลง","ตรวจพบการสั่นของจรวด","⚠️ ระบบกำลังส่งสัญญาณเตือน","🔴 ไฟเตือนทำงาน จรวดเอียงเล็กน้อย","⚠️ ภารกิจล้มเหลว"]; elements["rocket"].className = `rocket rocket-state-${gameState.mistakes}`; elements["rocket"].setAttribute("aria-label",notes[gameState.mistakes]); elements["rocket-note"].textContent = notes[gameState.mistakes]; }
function updateGameStatus() { if (!gameState.currentWord) return; elements["category-value"].textContent = gameState.currentWord.categoryName; elements["difficulty-value"].textContent = ({easy:"ง่าย",medium:"ปานกลาง",hard:"ยาก"})[gameState.selectedDifficulty]; elements["score-value"].textContent = gameState.score; elements["streak-value"].textContent = gameState.streak; elements["energy-value"].textContent = `${gameState.maxMistakes - gameState.mistakes}/${gameState.maxMistakes}`; elements["round-value"].textContent = gameState.roundNumber; const hard = gameState.selectedDifficulty === "hard"; elements["timer-card"].classList.toggle("is-hidden",!hard); if (hard) updateTimerDisplay(); }
function checkWin() { return [...gameState.currentWord.word].every(letter => gameState.guessedLetters.has(letter)); }
function checkLoss() { return gameState.mistakes >= gameState.maxMistakes; }
function useHint() { if (!gameState.gameActive || gameState.hintUsed) return; const hidden = [...new Set([...gameState.currentWord.word].filter(letter => !gameState.guessedLetters.has(letter)))]; if (!hidden.length) return; gameState.hintUsed = true; gameState.guessedLetters.add(hidden[Math.floor(Math.random() * hidden.length)]); gameState.roundScore = Math.max(0,gameState.roundScore - 20); gameState.score = Math.max(0,gameState.score - 20); elements["hint-button"].disabled = true; updateWordDisplay(); updateGameStatus(); showScoreFloat("-20 คำใบ้"); playSound("hint"); if (checkWin()) completeMission(); }
function calculateRoundScore() { const mission = 50; const energy = (gameState.maxMistakes - gameState.mistakes) * 10; const noHint = gameState.hintUsed ? 0 : 20; const streak = gameState.streak + 1 >= 2 ? (gameState.streak + 1) * 10 : 0; return {mission,energy,noHint,streak,total:mission + energy + noHint + streak}; }
function completeMission() { if (!gameState.gameActive) return; gameState.gameActive = false; stopTimer(); const bonus = calculateRoundScore(); gameState.streak += 1; gameState.roundScore += bonus.total; gameState.score += bonus.total; saveStats(true); updateGameStatus(); startCountdown(bonus); }
function failMission(message) { if (!gameState.gameActive) return; gameState.gameActive = false; stopTimer(); gameState.streak = 0; saveStats(false); updateRocketState(); updateGameStatus(); elements["mission-status"].textContent = message; playSound("failed"); window.setTimeout(() => showResultModal("failed"),500); }
function startCountdown(bonus) { const values = ["3","2","1","LAUNCH!"]; let index = 0; elements["mission-status"].textContent = "นับถอยหลังเพื่อปล่อยจรวด..."; const tick = () => { elements["countdown"].textContent = values[index]; elements["countdown"].classList.remove("pop"); void elements["countdown"].offsetWidth; elements["countdown"].classList.add("pop"); playSound(index < 3 ? "countdown" : "launch"); index += 1; if (index < values.length) window.setTimeout(tick,650); else window.setTimeout(() => launchRocket(bonus),600); }; tick(); }
function launchRocket(bonus) { elements["countdown"].textContent = ""; elements["rocket"].classList.add("launch"); elements["mission-status"].textContent = "MISSION COMPLETE! จรวดกำลังมุ่งสู่อวกาศ"; window.setTimeout(() => { elements["rocket"].className = "rocket rocket-state-0"; showResultModal("complete",bonus); },1750); }
function startTimer() { stopTimer(); updateTimerDisplay(); gameState.timerId = window.setInterval(() => { gameState.timeRemaining -= 1; updateTimerDisplay(); if (gameState.timeRemaining <= 0) failMission("หมดเวลาแล้ว ภารกิจสิ้นสุด"); },1000); }
function stopTimer() { if (gameState.timerId) { window.clearInterval(gameState.timerId); gameState.timerId = null; } }
function updateTimerDisplay() { elements["timer-value"].textContent = gameState.timeRemaining; elements["timer-card"].classList.toggle("warning",gameState.timeRemaining > 0 && gameState.timeRemaining <= 10); }
function showResultModal(type,bonus) { const won = type === "complete"; const word = gameState.currentWord; elements["result-icon"].textContent = won ? "🚀" : "⚠️"; elements["result-title"].textContent = won ? "MISSION COMPLETE" : "MISSION FAILED"; elements["result-subtitle"].textContent = won ? "ภารกิจสำเร็จ! คุณถอดรหัสคำศัพท์ได้ยอดเยี่ยม" : "ภารกิจยังไม่สำเร็จ แต่ลองใหม่ได้เสมอ"; elements["result-word"].textContent = word.word; elements["result-translation"].textContent = `คำแปล: ${word.translation}`; elements["result-example"].textContent = word.example; elements["retry-button"].classList.toggle("is-hidden",won); elements["next-button"].textContent = won ? "เล่นคำถัดไป" : "เล่นคำใหม่"; const lines = won ? [["คะแนนตัวอักษร",gameState.letterScore],["โบนัสภารกิจ",bonus.mission],["โบนัสพลังงาน",bonus.energy],["โบนัสไม่ใช้คำใบ้",bonus.noHint],["โบนัสชนะต่อเนื่อง",bonus.streak],["คะแนนรอบนี้",gameState.roundScore]] : [["คะแนนรอบนี้",gameState.roundScore],["คะแนนรวม",gameState.score]]; elements["score-breakdown"].innerHTML = lines.map(([label,value],index) => `<p class="${index === lines.length - 1 ? "total" : ""}"><span>${label}</span><strong>${value}</strong></p>`).join(""); elements["result-modal"].classList.add("is-open"); elements["result-modal"].setAttribute("aria-hidden","false"); if (won) playSound("complete"); }
function closeResultModal() { elements["result-modal"].classList.remove("is-open"); elements["result-modal"].setAttribute("aria-hidden","true"); }
function showStatsModal() { const stats = getStats(); const rate = stats.gamesPlayed ? Math.round(stats.gamesWon / stats.gamesPlayed * 100) : 0; elements["high-score-stat"].textContent = stats.highScore; elements["games-played-stat"].textContent = stats.gamesPlayed; elements["games-won-stat"].textContent = stats.gamesWon; elements["win-rate-stat"].textContent = `${rate}%`; elements["best-streak-stat"].textContent = stats.bestStreak; elements["stats-modal"].classList.add("is-open"); elements["stats-modal"].setAttribute("aria-hidden","false"); }
function closeStatsModal() { elements["stats-modal"].classList.remove("is-open"); elements["stats-modal"].setAttribute("aria-hidden","true"); }
function showNotification(message) { elements.notification.textContent = message; elements.notification.classList.add("show"); window.clearTimeout(noticeTimer); noticeTimer = window.setTimeout(() => elements.notification.classList.remove("show"),2600); }
function showScoreFloat(message) { elements["score-float"].textContent = message; elements["score-float"].classList.remove("show"); void elements["score-float"].offsetWidth; elements["score-float"].classList.add("show"); }
function updateSoundButton() { elements["sound-button"].textContent = gameState.soundEnabled ? "🔊" : "🔇"; elements["sound-button"].setAttribute("aria-label",gameState.soundEnabled ? "ปิดเสียง" : "เปิดเสียง"); elements["sound-button"].setAttribute("aria-pressed",String(gameState.soundEnabled)); }
function toggleSound() { gameState.soundEnabled = !gameState.soundEnabled; setStorage(keys.sound,gameState.soundEnabled); updateSoundButton(); if (gameState.soundEnabled) playSound("correct"); }
function playSound(type) { if (!gameState.soundEnabled) return; try { audioContext ||= new (window.AudioContext || window.webkitAudioContext)(); const sound = {correct:[660,.11,"sine"],wrong:[190,.18,"sawtooth"],hint:[490,.12,"triangle"],countdown:[440,.08,"sine"],launch:[180,.35,"sawtooth"],complete:[780,.22,"sine"],failed:[140,.25,"triangle"]}[type]; if (!sound) return; const [frequency,duration,wave] = sound; const oscillator = audioContext.createOscillator(); const gain = audioContext.createGain(); oscillator.type = wave; oscillator.frequency.setValueAtTime(frequency,audioContext.currentTime); if (type === "launch") oscillator.frequency.exponentialRampToValueAtTime(720,audioContext.currentTime + duration); gain.gain.setValueAtTime(.055,audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime + duration); oscillator.connect(gain).connect(audioContext.destination); oscillator.start(); oscillator.stop(audioContext.currentTime + duration); } catch { /* Audio is optional. */ } }
function initializeGame() { cacheDOMElements(); loadStats(); bindEvents(); updateSelections(); }
document.addEventListener("DOMContentLoaded",initializeGame);
