begin;

create extension if not exists pgcrypto;

create table if not exists public.issue_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9-]{2,40}$'),
  name text not null check (char_length(name) between 2 and 80),
  description text not null default '' check (char_length(description) <= 300),
  sort_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.issue_reports (
  id uuid primary key default gen_random_uuid(),
  category_id bigint not null references public.issue_categories(id),
  reporter_id uuid default auth.uid() references auth.users(id) on delete set null,
  title text not null check (char_length(title) between 5 and 140),
  description text not null check (char_length(description) between 10 and 4000),
  steps_to_reproduce text not null default '' check (char_length(steps_to_reproduce) <= 4000),
  page_url text not null default '' check (char_length(page_url) <= 800),
  browser_info text not null default '' check (char_length(browser_info) <= 800),
  status text not null default 'new' check (status in ('new', 'reviewing', 'resolved', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists issue_reports_created_at_idx on public.issue_reports (created_at desc);
create index if not exists issue_reports_status_idx on public.issue_reports (status);
create index if not exists issue_reports_category_idx on public.issue_reports (category_id);
create index if not exists issue_reports_reporter_idx on public.issue_reports (reporter_id);

create or replace function public.set_issue_report_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists issue_reports_set_updated_at on public.issue_reports;
create trigger issue_reports_set_updated_at
before update on public.issue_reports
for each row execute function public.set_issue_report_updated_at();

insert into public.issue_categories (slug, name, description, sort_order)
values
  ('login-account', 'บัญชีและการเข้าสู่ระบบ', 'สมัครบัญชี เข้าสู่ระบบ รหัสผ่าน และการยืนยันตัวตน', 10),
  ('classroom-students', 'ห้องเรียนและรายชื่อนักเรียน', 'การสร้างห้องเรียน นำเข้ารายชื่อ และข้อมูลนักเรียน', 20),
  ('attendance', 'เช็กชื่อและเวลาเรียน', 'การเช็กชื่อ สถานะมาเรียน และประวัติการเข้าเรียน', 30),
  ('scores-reports', 'คะแนนและรายงาน', 'การบันทึกคะแนน คำนวณผล และส่งออกรายงาน', 40),
  ('sync-data', 'การซิงก์และข้อมูล', 'การบันทึกบน Cloud ดาวน์โหลด และความสอดคล้องของข้อมูล', 50),
  ('games', 'เกมการศึกษา', 'การเข้าเกม การเล่น และการแสดงผลของเกม', 60),
  ('feature-request', 'ข้อเสนอแนะและฟีเจอร์', 'แนวคิดหรือความสามารถใหม่ที่อยากให้ ClassKru มี', 70),
  ('other', 'อื่น ๆ', 'ปัญหาหรือข้อเสนอแนะที่ไม่อยู่ในหมวดข้างต้น', 99)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order,
  is_active = true;

alter table public.issue_categories enable row level security;
alter table public.issue_reports enable row level security;

drop policy if exists "Authenticated users can read active issue categories" on public.issue_categories;
create policy "Authenticated users can read active issue categories"
on public.issue_categories for select
to authenticated
using (is_active = true);

drop policy if exists "Authenticated users can create their own issue reports" on public.issue_reports;
create policy "Authenticated users can create their own issue reports"
on public.issue_reports for insert
to authenticated
with check (reporter_id = auth.uid() and status = 'new');

drop policy if exists "Authenticated users can read their own issue reports" on public.issue_reports;
create policy "Authenticated users can read their own issue reports"
on public.issue_reports for select
to authenticated
using (reporter_id = auth.uid());

revoke all on table public.issue_categories from anon;
revoke all on table public.issue_reports from anon;
grant select on table public.issue_categories to authenticated;
grant select, insert on table public.issue_reports to authenticated;
grant usage, select on sequence public.issue_categories_id_seq to authenticated;

commit;
